version: '1'
services:
  backend:
    build: ./backend
    ports:
      - "5050:80"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5000:80"
    restart: always
    depends_on:
      - backend